package restaurantA;


enum customerState {FOLLOWING, WAITINGFORESCORT, FOODTABLE, SEATED, READY, ORDERING,
	ORDERED, WAITING, FOODREADY, EATING, FINISHED, DONE, REORDER, RECEIVEDCHECK, NEEDSCHECK, CHECKREADY}